var devel = 'devel/';
var deploy = 'deploy/';
var assetsSrc = devel + 'assets/';
var assetsDest = deploy + 'assets/';
var bower = 'bower_components/';
var offline = assetsDest + 'offline/';

var paths = {

	deploy: './' + deploy + '/**/*',

	html: {
		src: devel + '/**/*.+(html|md)',
		dest: deploy
	},

	handlebars: {
		src: devel + '/**/*.handlebars',
		partials: devel + 'templates/partials/',
		dest: deploy,
		watch: devel + '**/*.handlebars'
	},

	styles: {

		all: {
			src: assetsSrc + '_sass/main.scss',
			watch: assetsSrc + '_sass/**/*.+(scss|sass)',
			dest: assetsDest + 'generated/'
		}
	},

	scripts: {
		all: {
			src: assetsSrc + '_scripts/',
			watch: assetsSrc + '_scripts/**/*.js',
			dest: assetsDest + 'generated/'
		}
	},

	sassUtils: {

		bourbon: {
			src: bower + 'bourbon/core/**/*.+(scss|sass)',
			dest: assetsSrc + '_sass/utils/bourbon/'
		},
		bitters: {
			src: bower + 'bitters/core/**/*.+(scss|sass)',
			dest: assetsSrc + '_sass/utils/bitters/'
		},
		normalize: {
			src: bower + 'normalize-scss/**/*.+(scss|sass)',
			dest: assetsSrc + '_sass/utils/normalize/'
		}
	},

	libs: {
		jquery: {
			src: bower + 'jquery/dist/jquery.min.js',
			dest: assetsDest + 'offline/'
		},

		jquerySlim: {
			src: bower + 'jquery/dist/jquery.slim.min.js',
			dest: assetsDest + 'offline/'
		}

		// semantic: {
		// 	src: bower + 'semantic/dist/**/*',
		// 	dest: assetsDest + 'offline/semantic',
		// 	js: bower + 'semantic/dist/semantic.min.js'
		// },
		//
		// gsap: {
		// 	src: bower + 'gsap/src/minified/**/*.js',
		// 	dest: offline + 'gsap/'
		// }
	},

	data: {
		images: {
			src: assetsSrc + '_data/images/**/*.+(png|jpg|svg|gif)',
			dest: assetsDest + '_data/images/'
		},
		json: {
			src: assetsSrc + '_data/json/',
			dest: assetsDest + '_data/json/',
			watch: assetsSrc + '_data/json/**/*.json'
		},
		fonts: {
			src: assetsSrc + '_data/fonts/**/*.+(eot|svg|woff|woff2|ttf)',
			dest: assetsDest + '_data/fonts/'
		}
	},

	merged: {
		dest: assetsDest + 'offline/merged/'
	}
};


var renderedNames = {
	javascript: {

		/* MY MERGED JAVASCRIPT */
		scripts: 'scripts.js',

		/* MERGED LIBS */
		semantic:'semantic.min.js',
		all: 'libs.min.js'
	}
};

var ignoreModernizr = '!' + paths.scripts.all.src + 'autogenerated/modernizr.js';
var watchedJsFiles = [ignoreModernizr, paths.scripts.all.src];

module.exports = {
	paths: paths,
	ignoreModernizr: ignoreModernizr,
	watchedJsFiles: watchedJsFiles,
	renderedNames: renderedNames
};
